(load "/home/angel/sicp/exercises/3.28/or-gate.scm")
(load "/home/angel/sicp/exercises/3.29/and-gate.scm")

(define (half-adder a b s c)
  (let ((d (make-wire)) 
         (e (make-wire)))
    (or-gate a b d)
    (and-gate a b c)
    (and-gate d e s)
  'ok))
