(load "~/sicp/examples/1.1.7/square.scm")
(load "~/sicp/examples/1.1.7/abs.scm")
(load "~/sicp/examples/1.1.7/good-enough.scm")
(load "~/sicp/examples/1.1.7/improve.scm")
(load "~/sicp/examples/1.1.7/sqrt-iter.scm")
(define (sqrt x) (sqrt-iter 1.0 x))
