(define (* a b)
  (define (even? n) (= (remainder n 2) 0))
  (define (double x) (+ x x))
  (define (halve x) (/ x 2))
  (define (mul a b) 
    (cond
      ((= b 1) a)
      ((even? b) 
       (display "a: ") (display a) (display " - b: ") (display b) (newline)
       (mul (double a) (halve b)))
      (else (+ a (mul a (- b 1))))))
  (mul a b))
