(load "/home/angel/sicp/exercises/3.33/constrains.scm")

(define (averager a b c avg)
  (let
    ((1-third (make-connector))
     (one-third-a (make-connector))
     (one-third-b (make-connector))
     (one-third-c (make-connector))
     (ab (make-connector)))
    (constant (/ 1 3) 1-third)
    (multiplier a 1-third one-third-a)
    (multiplier b 1-third one-third-b)
    (multiplier c 1-third one-third-c)
    (adder one-third-a one-third-b ab)
    (adder ab one-third-c avg)
    'ok))
